name: deploy

on:
  push:
    branches: [ main ]


jobs:
  build-base:
    name: Build Base
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        run: |
          curl '${{ secrets.WEBHOOK_URL }}'